version: 2.1

snippets:
  main-only: &main-only
    filters:
      branches:
        only:
          - main
          - master
  big_resource_class: &big_resource_class
    resource_class: xlarge
    environment:
      GOMAXPROCS: 8
  go_image: &goimage cimg/go:1.20

executors:
  default:
    docker:
      - image: *goimage

jobs:
  test:
    macos:
      xcode: 1.0-test
    steps:
      - run: it
  lint:
    executor: default
    <<: *big_resource_class
    steps:
      - run:
          name: verify modules are tidy
          command: |
            go mod tidy -v
            git diff --exit-code
      - run: ./do lint-report ./... --timeout=2m

workflows:
  main:
    jobs:
      - test: *main-only
      - lint

--- # input above / compiled below

version: 2
jobs:
  test:
    steps:
      - run:
          command: it
    macos:
      xcode: 1.0-test
  lint:
    environment:
      GOMAXPROCS: 8
    steps:
      - run:
          command: |
            go mod tidy -v
            git diff --exit-code
          name: verify modules are tidy
      - run:
          command: ./do lint-report ./... --timeout=2m
    docker:
      - image: cimg/go:1.20

workflows:
  main:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - master
      - lint