version: 2.1

snippets:
  main-only: &main-only
    filters:
      branches:
        only:
          - main
          - master

jobs:
  test:
    macos:
      xcode: 1.0-test
    steps:
      - run: it

workflows:
  main:
    jobs:
      - test: *main-only

--- # input above / compiled below

version: 2
jobs:
  test:
    steps:
      - run:
          command: it
    macos:
      xcode: 1.0-test
workflows:
  main:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - master
