version: 2.1

jobs:
  test:
    docker:
      - image: my-image
    environment:
      TEST: test
    steps:
      - run: test
      - run: lint

workflows:
  main:
    jobs:
      - test

--- # input above / compiled below

version: 2
jobs:
  test:
    environment:
      TEST: test
    steps:
      - run:
          command: test
      - run:
          command: lint
    docker:
      - image: my-image
workflows:
  main:
    jobs:
      - test
