version: 2.1

jobs:
  build:
    docker:
      - image: go
    steps:
      - run: it

--- # input above / compiled below

version: 2
jobs:
  build:
    steps:
      - run:
          command: it
    docker:
      - image: go
workflows:
  workflow:
    jobs:
      - build
