version: 2.1

executors:
  example:
    docker:
      - image: my-image

jobs:
  one:
    executor: example
    steps:
      - run: do it
    environment:
      VAR: variable

  two:
    executor: example
    steps:
      - run: do it
    environment:
      - VAR: variable

  three:
    executor: example
    steps:
      - run: do it
    environment:
      - VAR=variable

workflows:
  main:
    jobs:
      - one
      - two
      - three

--- # input above / compiled below

version: 2
jobs:
  one:
    environment:
      VAR: variable
    steps:
      - run:
          command: do it
    docker:
      - image: my-image
  three:
    environment:
      VAR: variable
    steps:
      - run:
          command: do it
    docker:
      - image: my-image
  two:
    environment:
      VAR: variable
    steps:
      - run:
          command: do it
    docker:
      - image: my-image
workflows:
  main:
    jobs:
      - one
      - two
      - three
