version: 2.1

parameters:
  version:
    type: string
    default: v1
  tag:
    type: string
    default: testing

executors:
  util:
    docker:
      - image: internal/img

jobs:
  publish:
    executor: util
    steps:
      - run: publish <<pipeline.branch>>/<<pipeline.parameters.version>>-<<pipeline.parameters.tag>>

workflows:
  main:
    jobs:
      - publish

--- # pipeline parameters

branch: main
parameters:
  tag: prod

--- # input above / compiled below

version: 2
jobs:
  publish:
    steps:
      - run:
          command: publish main/v1-prod
    docker:
      - image: internal/img
workflows:
  main:
    jobs:
      - publish
