version: 2.1

jobs:
  test:
    docker:
      - image: go
    steps:
      - run
      - save_cache
      - save_cache:
          paths: [p1]
      - save_cache:
          key: key
      - restore_cache
      - store_artifacts
      - store_test_results
      - persist_to_workspace
      - persist_to_workspace:
          paths: [p1]
      - persist_to_workspace:
          root: root
      - attach_workspace

workflows:
  main:
    jobs:
      - test

--- # input above / error below

error: |-
  error processing workflow(s):
    - workflow main: job test: invalid step(s): 
      - position 0: run.command is required
      - position 1: errors within save_cache command:
        - save_cache.key is required
        - save_cache.paths requires at least 1 element
      - position 2: save_cache.key is required
      - position 3: save_cache.paths requires at least 1 element
      - position 4: restore_cache: requires one of key or keys to be present
      - position 5: store_artifacts.path is required
      - position 6: store_test_results.path is required
      - position 7: errors within persist_to_workspace command:
        - persist_to_workspace.paths requires at least 1 element
        - persist_to_workspace.root is required
      - position 8: persist_to_workspace.root is required
      - position 9: persist_to_workspace.paths requires at least 1 element
      - position 10: attach_workspace.at is required
