version: 2.1

jobs:
  test:
    docker:
      - image: go
    steps:
      - some-command

workflows:
  main:
    jobs:
      - test

--- # input above / error below

error: |-
  error processing workflow main: job test: failed to compiled step 0: some-command: command not found
