version: 2.1

jobs:
  test:
    parameters:
      image:
        type: enum
        enum: [go, node]
      required:
        type: boolean
      mismatch:
        type: string
    docker:
      - image: << parameters.image >>
    environment:
      MISMATCH: << parameters.mismatch >>
    steps:
      - run: do it

workflows:
  main:
    jobs:
      - test:
          image: ruby
          mismatch: 1.23
          not-declared: arg

--- # input above / error below

error: |-
  error processing workflow main: job test: parameter error(s):
    - enum mismatch for param image: wanted one of (go, node) but got ruby
    - missing required parameters: required
    - type mismatch for param mismatch: wanted string but got integer
    - unknown argument: not-declared
