version: 2.1

jobs:
  test:
    docker:
      - image: go
    steps:
      - run:
          command: echo hello world
          when: sometimes

workflows:
  main:
    jobs:
      - test

--- # input above / error below

error: |-
  error processing workflow(s):
    - workflow main: job test: invalid step(s): position 0: invalid when attribute: wanted one of always, on_success, or on_fail but got: sometimes
