version: 2.1

jobs:
  test:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: do it

workflows:
  main:
    jobs:
      - test:
          image: go

--- # input above / compiled below

version: 2
jobs:
  test:
    steps:
      - checkout
      - run:
          command: do it
    docker:
      - image: go
workflows:
  main:
    jobs:
      - test
